<a href="https://colab.research.google.com/github/won462/2026-1-BDA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.linspace(2,3)


array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [3]:
(3-1)/(50-1)

0.04081632653061224

In [5]:
np.linspace(2,3,2)

array([2., 3.])

In [7]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [ ]:
np.linspace(2,3,3,retstep= True)

In [11]:
a = np.linspace(2,3,3,retstep= True)
float(a[1])

0.5

In [13]:
np.linspace(2,3,3, retstep = True , endpoint=False)


(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

#numpy 주요 함수

In [14]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [15]:
np.zeros ((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [16]:
np.zeros((2,3),dype=int)

TypeError: zeros() got an unexpected keyword argument 'dype'

In [17]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [19]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [20]:
np.full((4,3) ,np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [21]:
import numpy as np
a= np.arange(3)
a

array([0, 1, 2])

In [22]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2 )

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [25]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b = np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [27]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


#고급색션

In [28]:
import numpy as np

x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[1]

np.int64(1)

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [31]:
x[[2]]

array([2])

In [32]:
x[[2,3]]

array([2, 3])

In [34]:
x[[2,3,2,5,8]]

array([2, 3, 2, 5, 8])

In [36]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [37]:
int(x[1,0])

8

In [39]:
x[...,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [40]:
x[0,1]

np.int64(1)

In [41]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [42]:
x[[1,3,5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [43]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [46]:
x[[1,2],[2,2]]

array([10, 26])

In [47]:
a = np.arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [48]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [54]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [55]:
a[np.arange(2,4)][:,[1,1,1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [56]:
a[np.arange(2,4)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [57]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])