<a href="https://colab.research.google.com/github/won462/2026-1-BDA/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1,6,2)
c

array([1, 3, 5])

In [ ]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
x

array([[1, 2, 3]])

In [ ]:
y

array([[4, 5, 6]])

In [ ]:
x.shape, y.shape

((1, 3), (1, 3))

In [ ]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
import numpy as np
rg = np.random.default_rng(12345)
rg.random() #[0,1]


Generator(PCG64) at 0x7EEDB9645A80

In [ ]:
import numpy as np
rng = np.random.default_rng(12345)
rng


Generator(PCG64) at 0x7EEDB96460A0

In [ ]:
rg.random()

0.22733602246716966

In [ ]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [ ]:
rg.random((3,4))

array([[0.05820261, 0.4087339 , 0.16862884, 0.24014406],
       [0.78000786, 0.2037676 , 0.55205095, 0.36699414],
       [0.50728172, 0.3334378 , 0.28272167, 0.2818303 ]])

In [ ]:
rg.random((2,3,4,))

array([[[0.08538129, 0.48181366, 0.88334289, 0.94722777],
        [0.02738372, 0.91775224, 0.12152453, 0.74784776],
        [0.89652074, 0.1679298 , 0.33146322, 0.37815663]],

       [[0.34684896, 0.5162557 , 0.00899403, 0.4226782 ],
        [0.87765773, 0.08740515, 0.48408482, 0.48122773],
        [0.78257149, 0.96455958, 0.70709644, 0.27373672]]])

In [ ]:
import numpy as np
rg = np.random.default_rng(1)
rg.integers(0,10,3)

array([4, 5, 7])

In [ ]:
rg.integers(1,7,(3,4))


array([[6, 1, 1, 5],
       [6, 2, 2, 6],
       [3, 2, 5, 2]])

In [ ]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [ ]:
rg.standard_normal((3,4))

array([[-1.30315723,  0.90535587,  0.44637457, -0.53695324],
       [ 0.5811181 ,  0.3645724 ,  0.2941325 ,  0.02842224],
       [ 0.54671299, -0.73645409, -0.16290995, -0.48211931]])

In [ ]:
rg.standard_normal(5)

array([ 0.59884621,  0.03972211, -0.29245675, -0.78190846, -0.25719224])

#배열 결합 연습

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10)
a,b,c


(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p = np.arange(1,7).reshape(2,3)
q = np.arange(11,17).reshape(2,3)
r = np.arange(21,27).reshape(2,3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack((q,p,r))

array([[11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hstack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a,b,c),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b,c),axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p,q,r),axis=0
        )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,r),axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r),axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r),axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [63]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
np.c_[p,q,r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [60]:
np.r_[p,q,r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [62]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.vstack((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])